name: Build and publish multi-arch Docker images ROS

on:
  workflow_dispatch:
  # push:
  #   branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Docker Buildx manually
        run: |
          # Устанавливаем зависимости
          sudo apt-get update -y
          sudo apt-get install -y docker-ce docker-ce-cli containerd.io

          # Проверим, есть ли buildx (в новых версиях Docker он уже встроен)
          docker buildx version || {
            echo "Installing Docker Buildx..."
            BUILDX_VERSION=$(curl -s https://api.github.com/repos/docker/buildx/releases/latest | grep tag_name | cut -d '"' -f 4)
            mkdir -p ~/.docker/cli-plugins/
            curl -SL "https://github.com/docker/buildx/releases/download/${BUILDX_VERSION}/buildx-${BUILDX_VERSION}.linux-amd64" -o ~/.docker/cli-plugins/docker-buildx
            chmod +x ~/.docker/cli-plugins/docker-buildx
          }

          # Активируем buildx
          docker buildx create --use --name mybuilder
          docker buildx inspect --bootstrap

      # --- Login to GHCR ---
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # --- Build mihomo_env_ros ---
      - name: Read version for mihomo_env_ros
        id: mihomo_env_ros_version
        run: echo "VERSION=$(cat ./mihomo_env_ros/VERSION)" >> $GITHUB_OUTPUT

      - name: Build and push mihomo_env_ros
        uses: docker/build-push-action@v4
        with:
          context: ./mihomo_env_ros
          file: ./mihomo_env_ros/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/vanes32/mihomo/mihomo_env_ros:latest
            ghcr.io/vanes32/mihomo/mihomo_env_ros:${{ steps.mihomo_env_ros_version.outputs.VERSION }}